version: '3'

services:
  arbc_app:
    container_name: ArBC-APP
    build: .
    #command: npm install
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules