site_name: ArBC
repo_name: '2019.2-ArBC'
repo_url: 'https://github.com/fga-eps-mds/2019.2-ArBC'

theme:
  name: 'material'
  language: 'pt'
  logo: 'imagens/Icone.png'
  favicon: 'imagens/ararat.png'
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'amber'

nav:
  - Início: index.md
  - Membros: membros.md
  - Download e Execução: Download.md
  - Especificações Técnicas: Especificacoes_Tecnicas.md
  - Integração Front e Back: Intergracao.md
  - Manual do Usuário: Manual_Usuario.md
  - Projeto:
      - Documento de Arquitetura: mds/Documento_de_arquitetura.md
      - Documento de Visão: mds/Documento_de_visao.md
      - Roadmap:
        - Projeto: eps/roadmap.md
        - DevOps: eps/roadmapDevops.md
        - Scrum Master: eps/roadmapScrumMaster.md
        - Product Owner: eps/roadmapProductOwner.md
        - Arquiteto: eps/roadmapArquiteto.md
      - EAP: EAP.md
      - Termo de Abertura do Projeto: Termo-Abertura-Projeto.md
      - EVM: EVM.md
  - Produto:
      - Backlog de Produto: Product-Backlog.md
      - Protótipo de Alta Fidelidade: mds/Protótipo_de_alta_fidelidade.md
      - Entrega Contínua: continuous_delivery.md
      - Teste de Usabilidade: Usabilidade.md
  - Gerência:
      - Plano de Comunicação: Plano-Comunicacao.md
      - Plano de Gerenciamento de Riscos: Plano-Gerenciamento-Riscos.md
      - Plano de Qualidade: quality.md
      - GQM: gqm.md
      - Post Mortem: Postmortem.md
  - Contribuição:
      - Como Contribuir: HOW_TO_CONTRIBUTE.md
      - Código de Conduta: CODE_OF_CONDUCT.md
      - Políticas:
        - Branch: policies/branches.md
        - Commit: policies/commits.md
        - Issue: policies/issues.md
        - Pull Request: policies/pull_requests.md
  - Sprints:
      - Sprint 0:
        - Planejamento: sprints/Planejamento-Sprint-0.md
        - Fechamento: sprints/Fechamento-Sprint-0.md
      - Sprint 1:
        - Planejamento: sprints/Planejamento-Sprint-1.md
        - Fechamento: sprints/Fechamento-Sprint-1.md
      - Sprint 2:
        - Planejamento: sprints/Planejamento-Sprint-2.md
        - Fechamento: sprints/Fechamento-Sprint-2.md
      - Sprint 3:
        - Planejamento: sprints/Planejamento-Sprint-3.md
        - Fechamento: sprints/Fechamento-Sprint-3.md
      - Sprint 4:
        - Planejamento: sprints/Planejamento-Sprint-4.md
        - Fechamento: sprints/Fechamento-Sprint-4.md
      - Sprint 5:
        - Planejamento: sprints/Planejamento-Sprint-5.md
        - Fechamento: sprints/Fechamento-Sprint-5.md
      - Sprint 6:
        - Planejamento: sprints/Planejamento-Sprint-6.md
        - Fechamento: sprints/Fechamento-Sprint-6.md
      - Sprint 7:
        - Planejamento: sprints/Planejamento-Sprint-7.md
        - Fechamento: sprints/Fechamento-Sprint-7.md
      - Sprint 8:
        - Planejamento: sprints/Planejamento-Sprint-8.md
        - Fechamento: sprints/Fechamento-Sprint-8.md
      - Sprint 9:
        - Planejamento: sprints/Planejamento-Sprint-9.md
        - Fechamento: sprints/Fechamento-Sprint-9.md
      - Sprint 10:
        - Planejamento: sprints/Planejamento-Sprint-10.md
        - Fechamento: sprints/Fechamento-Sprint-10.md
      - Sprint 11:
        - Planejamento: sprints/Planejamento-Sprint-11.md
        - Fechamento: sprints/Fechamento-Sprint-11.md
      - Sprint 12:
        - Planejamento: sprints/Planejamento-Sprint-12.md
        - Fechamento: sprints/Fechamento-Sprint-12.md

plugins:
  - search
  - minify:
      minify_html: true
